weather_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: db
      user: airflow
      password: airflow
      dbname: airflow_db
      schema: bronze
      port: 5432
      threads: 4
